### ISSUE TITLE
"SMTP > Well-known services" page status

### ISSUE THREAD

**Issue by Igloczek** [nodemailer/nodemailer-web#10]
I was wondering why https://nodemailer.com/smtp/well-known/ have a bit different layout than the rest of the page and why it's not visible in the side navigation.

I see in the source that this page is stored in `static` directory as HTML file, probably there was no time to rewrite it to markdown, but it shouldn't prevent from listing it in the side navigation 🤔

**Comment by max-programming** [comment]
I don't know why no one is looking at this issue here.

But the well known services page is available [here](https://community.nodemailer.com/2-0-0-beta/setup-smtp/well-known-services/)

**Comment by andris9** [comment]
Well known services is soft-deprecated. These will continue working indefinitely to guarantee backwards compatibility, but as a feature, t has not been included in the official documenation for years. The linked pages all apply for very old versions of Nodemailer.
